version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: projector-minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_REGION: ${MINIO_REGION}
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090

volumes:
  minio-data:
